name: Job Video Generator

on:
  schedule:
    - cron: '0 5 * * *'   # 3 vidéos à 5h UTC
    - cron: '0 12 * * *'  # 3 vidéos à 12h UTC
    - cron: '0 19 * * *'  # 4 vidéos à 19h UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run script
      run: python main.py

    - name: Delete old videos
      run: find outputs/ -type f -name "*.mp4" -mtime +7 -delete
      
jobs:
  slsa-provenance:
    name: Generate SLSA Provenance
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate provenance
        uses: slsa-framework/slsa-generic-generator@v1.3.0
        with:
          artifact-path: ./output/job-video.mp4
          artifact-type: binary
          upload-assets: true
          
